## zshrc file by me

## Setup Hombrew PATH
export PATH=$PATH:/usr/local/bin

## Setup CDPATH
export CDPATH=.:$HOME:$HOME/code/src/github.com

## Golang variables
export GOPATH=$HOME/code
export GOBIN=$HOME/code/bin
export PATH=$PATH:$GOPATH:$GOBIN

## Vim variables
export VIMRC=$HOME/.config/nvim/init.vim

## Add Zsh env var
export ZSH=/Users/erik.ferm/.oh-my-zsh
export ZSHRC=$HOME/.zshrc

## Set zsh theme
ZSH_THEME="clean"

## Add which zsh plugins to use 
plugins=(git)

## Source oh-my-zsh
source $ZSH/oh-my-zsh.sh

## Add aliases
alias vim=nvim
alias evr='vim $VIMRC'
alias ezr='vim $ZSHRC'
alias szr='source $ZSHRC'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/erik.ferm/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/erik.ferm/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/erik.ferm/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/erik.ferm/google-cloud-sdk/completion.zsh.inc'; fi
