## zshrc file by me
## Add Zsh env var
export ZSH=$HOME/.oh-my-zsh
export ZSHRC=$HOME/.zshrc

## Setup CDPATH
export CDPATH=.:$HOME:$HOME/code/src/github.com

## Set zsh theme
ZSH_THEME="clean"

source $HOME/.oh-my-zsh/oh-my-zsh.sh

## Add which zsh plugins to use 
plugins=(git)

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then source "$HOME/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then source "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

## source stuff 
source $HOME/.aliases
source $HOME/.envvars

